<?php
$en=require __DIR__.'/../en/frontend.php';
return array_replace_recursive($en,[
'site_defaults'=>['footer_text'=>'Wszelkie prawa zastrzeżone.','contact_intro'=>'Pomożemy znaleźć odpowiednią nieruchomość i odpowiemy na wszystkie pytania.','about_heading'=>'Nasze podejście','about_body'=>'Domatia oferuje wybrane nieruchomości oraz jasne, indywidualne wsparcie.','home_hero_badge'=>'Ekspercka obsługa, której możesz zaufać','home_hero_title'=>'Odkryj wyjątkowe nieruchomości','home_hero_subtitle'=>'W najbardziej pożądanych lokalizacjach','home_search_button_text'=>'Szukaj','home_value_1'=>'Starannie wybrane nieruchomości','home_value_2'=>'Indywidualne wsparcie od początku do końca','home_value_3'=>'Przejrzysty proces udanego zakupu','home_featured_heading'=>'Wyróżnione nieruchomości','home_featured_subtitle'=>'Starannie wybrane najlepsze oferty z naszego katalogu.','home_cta_heading'=>'Wspieramy Cię na każdym etapie zakupu','home_cta_body'=>'Od pierwszej wizyty do finalizacji zapewniamy jasne, indywidualne wsparcie.','home_cta_primary_text'=>'Zobacz nieruchomości','home_cta_secondary_text'=>'Kontakt','about_header_title'=>'O nas','contact_header_title'=>'Kontakt','environment_header_title'=>'Poznaj lokalizacje','register_header_title'=>'Utwórz konto'],
'common'=>['image_of'=>'Zdjęcie: :title','reference_short'=>'Nr ref.','pending'=>'Oczekuje','photos'=>'{1} :count zdjęcie|[2,4] :count zdjęcia|[5,*] :count zdjęć'],'contact'=>['map'=>'Mapa','phone_prefix'=>'Telefon:','email_prefix'=>'E-mail:'],'environment'=>['title'=>'Lokalizacje','intro'=>'Poznaj obsługiwane lokalizacje, ich otoczenie i dostępne nieruchomości.'],
'properties'=>['filter_title'=>'Filtruj nieruchomości','filter_intro'=>'Doprecyzuj wyszukiwanie, aby szybko znaleźć odpowiednią ofertę.','favorites_kicker'=>'Zapisany wybór','favorites_count'=>'{1} :count zapisana nieruchomość|[2,4] :count zapisane nieruchomości|[5,*] :count zapisanych nieruchomości','type_in_location'=>':type w :location','video'=>'Obejrzyj film','virtual_tour'=>'Wirtualny spacer','technical_sheet'=>'Szczegóły nieruchomości','highlighted_features'=>'Najważniejsze cechy','map_location'=>'Położenie na mapie','contact_default_message'=>'Zapytanie o nieruchomość :title (:reference)','name_placeholder'=>'Twoje imię','features'=>['pool'=>'Basen','patio'=>'Ogród lub patio','plot_available'=>'Dostępna działka','plot_area'=>'Działka :area m²','air_conditioning'=>'Klimatyzacja','garage'=>'Garaż','lift'=>'Winda','parking'=>'Miejsce parkingowe','terrace'=>'Taras','garden'=>'Ogród','solarium'=>'Taras słoneczny','storage_room'=>'Komórka lokatorska','furnished'=>'Umeblowana','sea_views'=>'Widok na morze','new_build'=>'Nowe budownictwo','featured'=>'Wyróżniona nieruchomość'],'details'=>['town'=>'Miejscowość','province'=>'Prowincja','country'=>'Kraj','location_detail'=>'Szczegółowa lokalizacja','price'=>'Cena','operation'=>'Transakcja','energy_consumption'=>'Zużycie energii','emissions'=>'Emisje','reference'=>'Numer referencyjny','source_date'=>'Data źródłowa']],
'profile_page'=>['kicker'=>'Konto','title'=>'Mój profil','intro'=>'Zarządzaj danymi i bezpieczeństwem konta w jednym miejscu.','back_to_backoffice'=>'Wróć do panelu','back_home'=>'Wróć na stronę główną','role'=>'Rola','email_status'=>'Status e-maila','verified'=>'Potwierdzony','verification_pending'=>'Oczekuje na potwierdzenie','member_since'=>'Użytkownik od','no_date'=>'Brak daty','manage_account'=>'Zarządzaj kontem','go_to_settings'=>'Przejdź do ustawień','verification_sent'=>'Wysłaliśmy nowy link potwierdzający.'],
'profile'=>['access_title'=>'Dane dostępu','access_intro'=>'Zaktualizuj nazwę i główny adres e-mail.','full_name'=>'Imię i nazwisko','email'=>'E-mail','email_unverified'=>'Adres e-mail nie został potwierdzony.','email_verify_help'=>'Potwierdź adres, aby zabezpieczyć konto.','resend_link'=>'Wyślij link ponownie','save_changes'=>'Zapisz zmiany','profile_updated'=>'Profil zaktualizowany','security_title'=>'Bezpieczeństwo konta','security_intro'=>'Używaj silnego hasła.','current_password'=>'Aktualne hasło','new_password'=>'Nowe hasło','confirm_password'=>'Potwierdź nowe hasło','update_password'=>'Zmień hasło','password_updated'=>'Hasło zostało zmienione','danger_title'=>'Usuń konto','danger_intro'=>'Ta operacja trwale usuwa dostęp.','delete_password'=>'Aktualne hasło do potwierdzenia','password_placeholder'=>'Wpisz hasło','delete_warning'=>'Usunięcia nie można cofnąć.','delete_account'=>'Usuń konto'],
]);
