<?php
$en = require __DIR__.'/../en/ui.php';
return array_replace_recursive($en, [
 'nav'=>['home'=>'Strona główna','properties'=>'Nieruchomości','about'=>'O nas','environment'=>'Lokalizacje','contact'=>'Kontakt','favorites'=>'Ulubione','language'=>'Język'],
 'common'=>['search'=>'Szukaj','show'=>'Pokaż','apply_filters'=>'Zastosuj filtry','reset_filters'=>'Wyczyść filtry','more_filters'=>'Więcej filtrów','contact_us'=>'Skontaktuj się z nami','send_message'=>'Wyślij wiadomość','send_request'=>'Wyślij zapytanie','view_favorites'=>'Zobacz ulubione','view_catalog'=>'Zobacz ofertę','save'=>'Zapisz','from'=>'Od','to'=>'Do','explore_properties'=>'Przeglądaj nieruchomości','featured'=>'Wyróżniona'],
 'home'=>['title'=>'Strona główna','quick_search_title'=>'Znajdź swój przyszły dom','search_placeholder'=>'Lokalizacja, miasto, numer referencyjny…','any_zone'=>'Wszystkie lokalizacje','any_type'=>'Wszystkie typy','max_budget'=>'Maksymalny budżet','any_budget'=>'Dowolna cena','properties_count'=>':count nieruchomości','location_placeholder'=>'Lokalizacja','property_type'=>'Typ nieruchomości','min_price'=>'Od EUR','max_price'=>'Do EUR','latest_heading'=>'Najnowsze nieruchomości','latest_subtitle'=>'Najnowsze oferty w naszym katalogu.'],
 'properties'=>['page_title'=>'Nieruchomości na sprzedaż','intro'=>'Przeglądaj ofertę i zapisuj ulubione nieruchomości jednym kliknięciem.','empty'=>'Nie znaleziono nieruchomości.','featured_space'=>'Powierzchnia do potwierdzenia','location_pending'=>'Lokalizacja do potwierdzenia','type_fallback'=>'Nieruchomość','summary_title'=>'Szybki przegląd','summary_labels'=>['type'=>'Typ','space'=>'Przestrzeń','operation'=>'Dostępność','default'=>'Podsumowanie'],'description_title'=>'Opis nieruchomości','description_intro'=>'Czytelny przegląd zalet tej nieruchomości i powodów, dla których może Ci odpowiadać.','description_pending'=>'Przygotowujemy pełny opis tej nieruchomości.','related'=>'Podobne nieruchomości','related_subtitle'=>'Więcej ofert w tej lokalizacji lub kategorii.','contact_title'=>'Poproś o informacje','contact_intro'=>'Napisz, jak mamy się z Tobą skontaktować w sprawie :title.','name'=>'Imię i nazwisko','email'=>'E-mail','phone'=>'Telefon','accept_terms'=>'Zgadzam się na wykorzystanie moich danych do obsługi tego zapytania.','request_information'=>'Poproś o informacje','favorites_title'=>'Ulubione nieruchomości','favorites_intro'=>'Tutaj szybko wrócisz do zapisanych ofert.','favorites_empty_title'=>'Nie masz jeszcze ulubionych nieruchomości','favorites_empty_body'=>'Oferty oznaczone jako ulubione pojawią się tutaj.','saved'=>'Zapisana','favorite'=>'Ulubiona','favorite_added'=>'Dodano nieruchomość do ulubionych.','favorite_removed'=>'Usunięto nieruchomość z ulubionych.','bedrooms'=>'Sypialnie','bathrooms'=>'Łazienki','surface'=>'Powierzchnia','type'=>'Typ','photos'=>'zdjęcie|zdjęcia','results_count'=>'{0} Brak wyników|{1} :count nieruchomość|[2,4] :count nieruchomości|[5,*] :count nieruchomości','stats'=>['bedrooms_short'=>'syp.','bathrooms_short'=>'łaz.'],'sort'=>['title'=>'Sortowanie i wyniki','subtitle'=>'Uporządkuj listę, aby szybciej znaleźć odpowiednią nieruchomość.','label'=>'Sortuj według','latest'=>'Najnowsze','price_asc'=>'Cena: rosnąco','price_desc'=>'Cena: malejąco','area_desc'=>'Powierzchnia: malejąco','area_asc'=>'Powierzchnia: rosnąco','oldest'=>'Najstarsze'],'filters'=>['search'=>'Wyszukiwanie','search_placeholder'=>'Lokalizacja, numer, tytuł lub adres','type'=>'Typ nieruchomości','zone'=>'Lokalizacja','minimum_area'=>'Minimalna powierzchnia','town'=>'Miejscowość','price_range'=>'Zakres cen','min_price'=>'Cena minimalna','max_price'=>'Cena maksymalna','features'=>'Udogodnienia','others'=>'Pozostałe','bedrooms'=>'Sypialnie','bathrooms'=>'Łazienki','select'=>'Wybierz','pool'=>'Basen','terrace'=>'Taras','garden'=>'Ogród','solar'=>'Działka','patio'=>'Patio','up_to'=>'Do :price EUR']],
 'about'=>['title'=>'O nas','contact_title'=>'Skontaktuj się z nami','name'=>'Twoje imię','email'=>'Twój e-mail','message'=>'Twoja wiadomość','name_placeholder'=>'Wpisz imię','email_placeholder'=>'przyklad@email.com','message_placeholder'=>'Napisz wiadomość'],
 'contact'=>['title'=>'Kontakt','info_title'=>'Dane kontaktowe','message_title'=>'Wyślij nam wiadomość','phone_pending'=>'Jeszcze nie ustawiono','email_pending'=>'Jeszcze nie ustawiono','address_pending'=>'Adres nie został ustawiony','name'=>'Imię','email'=>'E-mail','message'=>'Wiadomość','name_placeholder'=>'Wpisz imię','email_placeholder'=>'Wpisz e-mail','message_placeholder'=>'Napisz wiadomość','accept_terms'=>'Akceptuję warunki','success'=>'Dziękujemy za wiadomość. Wkrótce się skontaktujemy.'],
 'environment'=>['title'=>'Lokalizacje','intro'=>'Poznaj lokalizacje, w których działamy, ich otoczenie, styl życia i dostępne nieruchomości.','interactive_map'=>'Mapa interaktywna','properties_in'=>'Nieruchomości w :name','view_more'=>'Zobacz więcej'],
 'search'=>['title'=>'Wyniki wyszukiwania','heading'=>'Wyniki wyszukiwania','empty'=>'Brak nieruchomości pasujących do wyszukiwania.','view_more'=>'Zobacz więcej'],
 'auth'=>['register_title'=>'Utwórz konto','register_heading'=>'Rejestracja','login_title'=>'Zaloguj się','login_heading'=>'Witaj ponownie','remember_me'=>'Zapamiętaj mnie','forgot_password'=>'Nie pamiętasz hasła?','forgot_password_intro'=>'Podaj e-mail, a wyślemy link do ustawienia nowego hasła.','send_reset_link'=>'Wyślij link','reset_password'=>'Ustaw nowe hasło','verify_email_intro'=>'Potwierdź adres e-mail za pomocą wysłanego linku.','verify_email_sent'=>'Nowy link potwierdzający został wysłany.','resend_verification'=>'Wyślij link ponownie','logout'=>'Wyloguj się','confirm_password_intro'=>'To zabezpieczona sekcja. Potwierdź hasło, aby kontynuować.','confirm'=>'Potwierdź','full_name'=>'Imię i nazwisko','email'=>'E-mail','password'=>'Hasło','confirm_password'=>'Potwierdź hasło','role'=>'Rola','user'=>'Użytkownik','admin'=>'Administrator','create_account'=>'Utwórz konto','already_have_account'=>'Masz już konto?','login'=>'Zaloguj się'],
 'property_types'=>['piso'=>'Apartament','casa'=>'Dom','villa'=>'Willa'],
]);
