<?php

return [
    'site_defaults' => ['footer_text'=>'All rights reserved.','contact_intro'=>'We are here to help you find the right property and answer your questions.','about_heading'=>'Our approach','about_body'=>'At Domatia we offer selected properties with a personal, clear and tailored service.','home_hero_badge'=>'Property expertise you can trust','home_hero_title'=>'Discover exceptional properties','home_hero_subtitle'=>'In the most sought-after destinations','home_search_button_text'=>'Search','home_value_1'=>'Carefully selected properties','home_value_2'=>'Personal guidance from start to finish','home_value_3'=>'A clear process focused on a successful purchase','home_featured_heading'=>'Featured properties','home_featured_subtitle'=>'A considered selection to begin with the best of our catalogue.','home_cta_heading'=>'With you at every step of the purchase','home_cta_body'=>'From the first viewing to completion, we provide clear and personal guidance.','home_cta_primary_text'=>'View properties','home_cta_secondary_text'=>'Contact us','about_header_title'=>'About us','contact_header_title'=>'Contact us','environment_header_title'=>'Explore the areas','register_header_title'=>'Create account'],
    'common' => ['image_of' => 'Image of :title', 'reference_short' => 'Ref.', 'pending' => 'Pending', 'photos' => '{1} :count photo|[2,*] :count photos'],
    'contact' => ['map' => 'Map', 'phone_prefix' => 'Phone:', 'email_prefix' => 'Email:'],
    'profile_page' => ['kicker'=>'Account','title'=>'My profile','intro'=>'Keep your details up to date, strengthen access security and manage your account in one place.','back_to_backoffice'=>'Back to backoffice','back_home'=>'Back to home','role'=>'Role','email_status'=>'Email status','verified'=>'Verified','verification_pending'=>'Awaiting verification','member_since'=>'Member since','no_date'=>'No date','manage_account'=>'Manage account','go_to_settings'=>'Go to settings','verification_sent'=>'We have sent a new verification link to your email.'],
    'environment' => ['title' => 'Areas', 'intro' => 'Discover the areas where we work, their lifestyle and surroundings, and the properties available in each one.'],
    'properties' => [
        'filter_title' => 'Filter properties', 'filter_intro' => 'Refine your search to quickly find the properties that suit you.',
        'favorites_kicker' => 'Saved selection', 'favorites_count' => '{1} :count saved property|[2,*] :count saved properties',
        'type_in_location' => ':type in :location', 'video' => 'Watch video', 'virtual_tour' => 'View virtual tour',
        'technical_sheet' => 'Property details', 'highlighted_features' => 'Highlighted features', 'map_location' => 'Location on the map',
        'contact_default_message' => 'Information request about :title (:reference)', 'name_placeholder' => 'Your name',
        'features' => ['pool'=>'Pool','patio'=>'Garden or patio','plot_available'=>'Plot available','plot_area'=>':area m² plot','air_conditioning'=>'Air conditioning','garage'=>'Garage','lift'=>'Lift','parking'=>'Parking','terrace'=>'Terrace','garden'=>'Garden','solarium'=>'Solarium','storage_room'=>'Storage room','furnished'=>'Furnished','sea_views'=>'Sea views','new_build'=>'New build','featured'=>'Featured property'],
        'details' => ['town'=>'Town','province'=>'Province','country'=>'Country','location_detail'=>'Detailed area','price'=>'Price','operation'=>'Transaction','energy_consumption'=>'Energy consumption','emissions'=>'Emissions','reference'=>'Reference','source_date'=>'Source date'],
    ],
    'profile' => ['access_title'=>'Access information','access_intro'=>'Update the display name and primary email linked to your account.','full_name'=>'Full name','email'=>'Email address','email_unverified'=>'Email address awaiting verification.','email_verify_help'=>'Verify the address to finish securing your account.','resend_link'=>'Resend link','save_changes'=>'Save changes','profile_updated'=>'Profile updated successfully','security_title'=>'Account security','security_intro'=>'Use a strong password to keep your account protected.','current_password'=>'Current password','new_password'=>'New password','confirm_password'=>'Confirm new password','update_password'=>'Update password','password_updated'=>'Password updated successfully','danger_title'=>'Delete account','danger_intro'=>'This permanently removes access. Only continue if you are completely sure.','delete_password'=>'Current password to confirm','password_placeholder'=>'Enter your password','delete_warning'=>'Deletion is irreversible and removes the data linked to the account.','delete_account'=>'Delete account'],
];
