<?php
$en=require __DIR__.'/../en/frontend.php';
return array_replace_recursive($en,[
'site_defaults'=>['footer_text'=>'Alle rettigheder forbeholdes.','contact_intro'=>'Vi hjælper dig med at finde den rette bolig og besvarer dine spørgsmål.','about_heading'=>'Vores tilgang','about_body'=>'Domatia tilbyder udvalgte boliger med klar og personlig rådgivning.','home_hero_badge'=>'Boligrådgivning du kan stole på','home_hero_title'=>'Oplev enestående boliger','home_hero_subtitle'=>'På de mest eftertragtede destinationer','home_search_button_text'=>'Søg','home_value_1'=>'Omhyggeligt udvalgte boliger','home_value_2'=>'Personlig rådgivning fra start til slut','home_value_3'=>'En klar proces mod et vellykket køb','home_featured_heading'=>'Udvalgte boliger','home_featured_subtitle'=>'Et nøje udvalg af det bedste i vores katalog.','home_cta_heading'=>'Vi følger dig gennem hele købet','home_cta_body'=>'Fra første fremvisning til afslutning tilbyder vi klar og personlig rådgivning.','home_cta_primary_text'=>'Se boliger','home_cta_secondary_text'=>'Kontakt','about_header_title'=>'Om os','contact_header_title'=>'Kontakt os','environment_header_title'=>'Oplev områderne','register_header_title'=>'Opret konto'],
'common'=>['image_of'=>'Billede af :title','reference_short'=>'Ref.','pending'=>'Afventer','photos'=>'{1} :count foto|[2,*] :count fotos'],'contact'=>['map'=>'Kort','phone_prefix'=>'Telefon:','email_prefix'=>'E-mail:'],'environment'=>['title'=>'Områder','intro'=>'Oplev vores områder, deres omgivelser og de tilgængelige boliger.'],
'properties'=>['filter_title'=>'Filtrer boliger','filter_intro'=>'Tilpas søgningen for hurtigt at finde den rette bolig.','favorites_kicker'=>'Gemt udvalg','favorites_count'=>'{1} :count gemt bolig|[2,*] :count gemte boliger','type_in_location'=>':type i :location','video'=>'Se video','virtual_tour'=>'Virtuel rundvisning','technical_sheet'=>'Boligdetaljer','highlighted_features'=>'Vigtige faciliteter','map_location'=>'Placering på kortet','contact_default_message'=>'Forespørgsel om :title (:reference)','name_placeholder'=>'Dit navn','features'=>['pool'=>'Pool','patio'=>'Have eller gårdhave','plot_available'=>'Grund tilgængelig','plot_area'=>':area m² grund','air_conditioning'=>'Aircondition','garage'=>'Garage','lift'=>'Elevator','parking'=>'Parkering','terrace'=>'Terrasse','garden'=>'Have','solarium'=>'Solterrasse','storage_room'=>'Depotrum','furnished'=>'Møbleret','sea_views'=>'Havudsigt','new_build'=>'Nybyggeri','featured'=>'Udvalgt bolig'],'details'=>['town'=>'By','province'=>'Provins','country'=>'Land','location_detail'=>'Detaljeret område','price'=>'Pris','operation'=>'Handel','energy_consumption'=>'Energiforbrug','emissions'=>'Udledning','reference'=>'Reference','source_date'=>'Kildedato']],
'profile_page'=>['kicker'=>'Konto','title'=>'Min profil','intro'=>'Administrer dine oplysninger og kontosikkerhed ét sted.','back_to_backoffice'=>'Tilbage til administration','back_home'=>'Tilbage til forsiden','role'=>'Rolle','email_status'=>'E-mailstatus','verified'=>'Bekræftet','verification_pending'=>'Afventer bekræftelse','member_since'=>'Medlem siden','no_date'=>'Ingen dato','manage_account'=>'Administrer konto','go_to_settings'=>'Gå til indstillinger','verification_sent'=>'Et nyt bekræftelseslink er sendt.'],
'profile'=>['access_title'=>'Adgangsoplysninger','access_intro'=>'Opdater navn og primær e-mailadresse.','full_name'=>'Fulde navn','email'=>'E-mailadresse','email_unverified'=>'E-mailadressen er ikke bekræftet.','email_verify_help'=>'Bekræft adressen for at beskytte kontoen.','resend_link'=>'Send link igen','save_changes'=>'Gem ændringer','profile_updated'=>'Profilen er opdateret','security_title'=>'Kontosikkerhed','security_intro'=>'Brug en stærk adgangskode.','current_password'=>'Nuværende adgangskode','new_password'=>'Ny adgangskode','confirm_password'=>'Bekræft ny adgangskode','update_password'=>'Opdater adgangskode','password_updated'=>'Adgangskoden er opdateret','danger_title'=>'Slet konto','danger_intro'=>'Dette fjerner din adgang permanent.','delete_password'=>'Nuværende adgangskode til bekræftelse','password_placeholder'=>'Indtast din adgangskode','delete_warning'=>'Sletningen kan ikke fortrydes.','delete_account'=>'Slet konto'],
]);
