<?php
$en = require __DIR__.'/../en/ui.php';
return array_replace_recursive($en, [
 'nav'=>['home'=>'Forside','properties'=>'Boliger','about'=>'Om os','environment'=>'Områder','contact'=>'Kontakt','favorites'=>'Favoritter','language'=>'Sprog'],
 'common'=>['search'=>'Søg','show'=>'Vis','apply_filters'=>'Anvend filtre','reset_filters'=>'Nulstil filtre','more_filters'=>'Flere filtre','contact_us'=>'Kontakt os','send_message'=>'Send besked','send_request'=>'Send forespørgsel','view_favorites'=>'Se favoritter','view_catalog'=>'Se boliger','save'=>'Gem','from'=>'Fra','to'=>'Til','explore_properties'=>'Udforsk boliger','featured'=>'Udvalgt'],
 'home'=>['title'=>'Forside','quick_search_title'=>'Find dit næste hjem','search_placeholder'=>'Område, by, reference…','any_zone'=>'Alle områder','any_type'=>'Alle boligtyper','max_budget'=>'Maksimalt budget','any_budget'=>'Alle priser','properties_count'=>':count boliger','location_placeholder'=>'Placering','property_type'=>'Boligtype','min_price'=>'Fra EUR','max_price'=>'Til EUR','latest_heading'=>'Nyeste boliger','latest_subtitle'=>'De seneste boliger i vores katalog.'],
 'properties'=>['page_title'=>'Boliger til salg','intro'=>'Udforsk kataloget og gem dine favoritter med ét klik.','empty'=>'Ingen boliger fundet.','featured_space'=>'Areal afventer','location_pending'=>'Placering afventer','type_fallback'=>'Bolig','summary_title'=>'Kort overblik','summary_labels'=>['type'=>'Type','space'=>'Plads','operation'=>'Tilgængelighed','default'=>'Overblik'],'description_title'=>'Boligbeskrivelse','description_intro'=>'Et klart overblik over, hvad boligen tilbyder, og hvorfor den kan passe til dig.','description_pending'=>'Vi er ved at færdiggøre den fulde beskrivelse.','related'=>'Lignende boliger','related_subtitle'=>'Flere muligheder i samme område eller kategori.','contact_title'=>'Anmod om oplysninger','contact_intro'=>'Fortæl os, hvordan vi kan kontakte dig om :title.','name'=>'Fulde navn','email'=>'E-mail','phone'=>'Telefon','accept_terms'=>'Jeg accepterer, at mine oplysninger bruges til at besvare denne forespørgsel.','request_information'=>'Anmod om oplysninger','favorites_title'=>'Dine favoritboliger','favorites_intro'=>'Her kan du hurtigt finde tilbage til gemte boliger.','favorites_empty_title'=>'Du har endnu ikke gemt boliger','favorites_empty_body'=>'Boliger markeret som favoritter vises her.','saved'=>'Gemt','favorite'=>'Favorit','favorite_added'=>'Boligen er føjet til favoritter.','favorite_removed'=>'Boligen er fjernet fra favoritter.','bedrooms'=>'Soveværelser','bathrooms'=>'Badeværelser','surface'=>'Areal','type'=>'Type','photos'=>'foto|fotos','results_count'=>'{0} Ingen resultater|{1} :count bolig|[2,*] :count boliger','stats'=>['bedrooms_short'=>'sov.','bathrooms_short'=>'bad.'],'sort'=>['title'=>'Sortering og resultater','subtitle'=>'Sorter listen for hurtigere at finde den rigtige bolig.','label'=>'Sorter efter','latest'=>'Nyeste først','price_asc'=>'Pris: lav til høj','price_desc'=>'Pris: høj til lav','area_desc'=>'Areal: størst først','area_asc'=>'Areal: mindst først','oldest'=>'Ældste først'],'filters'=>['search'=>'Fritekstsøgning','search_placeholder'=>'Område, reference, titel eller placering','type'=>'Boligtype','zone'=>'Område','minimum_area'=>'Minimumsareal','town'=>'By','price_range'=>'Prisinterval','min_price'=>'Minimumspris','max_price'=>'Maksimumspris','features'=>'Faciliteter','others'=>'Andet','bedrooms'=>'Soveværelser','bathrooms'=>'Badeværelser','select'=>'Vælg','pool'=>'Pool','terrace'=>'Terrasse','garden'=>'Have','solar'=>'Grund','patio'=>'Gårdhave','up_to'=>'Op til :price EUR']],
 'about'=>['title'=>'Om os','contact_title'=>'Kontakt os','name'=>'Dit navn','email'=>'Din e-mail','message'=>'Din besked','name_placeholder'=>'Indtast dit navn','email_placeholder'=>'eksempel@email.com','message_placeholder'=>'Skriv din besked'],
 'contact'=>['title'=>'Kontakt','info_title'=>'Kontaktoplysninger','message_title'=>'Send os en besked','phone_pending'=>'Ikke angivet endnu','email_pending'=>'Ikke angivet endnu','address_pending'=>'Adresse ikke angivet','name'=>'Navn','email'=>'E-mail','message'=>'Besked','name_placeholder'=>'Indtast dit navn','email_placeholder'=>'Indtast din e-mail','message_placeholder'=>'Skriv din besked','accept_terms'=>'Jeg accepterer vilkårene','success'=>'Tak for din besked. Vi kontakter dig snart.'],
 'environment'=>['title'=>'Områder','intro'=>'Oplev områderne, hvor vi arbejder, deres livsstil, omgivelser og tilgængelige boliger.','interactive_map'=>'Interaktivt kort','properties_in'=>'Boliger i :name','view_more'=>'Se mere'],
 'search'=>['title'=>'Søgeresultater','heading'=>'Søgeresultater','empty'=>'Ingen boliger matcher din søgning.','view_more'=>'Se mere'],
 'auth'=>['register_title'=>'Opret konto','register_heading'=>'Registrer','login_title'=>'Log ind','login_heading'=>'Velkommen tilbage','remember_me'=>'Husk mig','forgot_password'=>'Glemt adgangskode?','forgot_password_intro'=>'Indtast din e-mail, så sender vi et link til at nulstille adgangskoden.','send_reset_link'=>'Send nulstillingslink','reset_password'=>'Nulstil adgangskode','verify_email_intro'=>'Bekræft din e-mail via det link, vi har sendt.','verify_email_sent'=>'Et nyt bekræftelseslink er sendt.','resend_verification'=>'Send bekræftelse igen','logout'=>'Log ud','confirm_password_intro'=>'Dette er et beskyttet område. Bekræft adgangskoden for at fortsætte.','confirm'=>'Bekræft','full_name'=>'Fulde navn','email'=>'E-mail','password'=>'Adgangskode','confirm_password'=>'Bekræft adgangskode','role'=>'Rolle','user'=>'Bruger','admin'=>'Administrator','create_account'=>'Opret konto','already_have_account'=>'Har du allerede en konto?','login'=>'Log ind'],
 'property_types'=>['piso'=>'Lejlighed','casa'=>'Hus','villa'=>'Villa'],
]);
