<?php
$en=require __DIR__.'/../en/frontend.php';
return array_replace_recursive($en,[
'site_defaults'=>['footer_text'=>'Alle rechten voorbehouden.','contact_intro'=>'Wij helpen u graag de juiste woning te vinden en beantwoorden al uw vragen.','about_heading'=>'Onze aanpak','about_body'=>'Domatia biedt geselecteerde woningen met persoonlijke, heldere begeleiding.','home_hero_badge'=>'Vastgoedexpertise waarop u kunt vertrouwen','home_hero_title'=>'Ontdek bijzondere woningen','home_hero_subtitle'=>'Op de meest gewilde locaties','home_search_button_text'=>'Zoeken','home_value_1'=>'Zorgvuldig geselecteerde woningen','home_value_2'=>'Persoonlijke begeleiding van begin tot eind','home_value_3'=>'Een helder proces voor een succesvolle aankoop','home_featured_heading'=>'Uitgelichte woningen','home_featured_subtitle'=>'Een zorgvuldige selectie van het beste uit ons aanbod.','home_cta_heading'=>'Wij begeleiden u bij elke stap','home_cta_body'=>'Van de eerste bezichtiging tot de overdracht bieden wij heldere, persoonlijke begeleiding.','home_cta_primary_text'=>'Woningen bekijken','home_cta_secondary_text'=>'Contact','about_header_title'=>'Over ons','contact_header_title'=>'Contact','environment_header_title'=>'Ontdek de regio’s','register_header_title'=>'Account aanmaken'],
'common'=>['image_of'=>'Afbeelding van :title','reference_short'=>'Ref.','pending'=>'In afwachting','photos'=>'{1} :count foto|[2,*] :count foto’s'],'contact'=>['map'=>'Kaart','phone_prefix'=>'Telefoon:','email_prefix'=>'E-mail:'],'environment'=>['title'=>'Regio’s','intro'=>'Ontdek onze regio’s, hun leefomgeving en het beschikbare woningaanbod.'],
'properties'=>['filter_title'=>'Woningen filteren','filter_intro'=>'Verfijn uw zoekopdracht om snel een passende woning te vinden.','favorites_kicker'=>'Bewaarde selectie','favorites_count'=>'{1} :count bewaarde woning|[2,*] :count bewaarde woningen','type_in_location'=>':type in :location','video'=>'Video bekijken','virtual_tour'=>'Virtuele rondleiding','technical_sheet'=>'Woningdetails','highlighted_features'=>'Belangrijkste kenmerken','map_location'=>'Locatie op de kaart','contact_default_message'=>'Informatieaanvraag over :title (:reference)','name_placeholder'=>'Uw naam','features'=>['pool'=>'Zwembad','patio'=>'Tuin of patio','plot_available'=>'Perceel beschikbaar','plot_area'=>':area m² perceel','air_conditioning'=>'Airconditioning','garage'=>'Garage','lift'=>'Lift','parking'=>'Parkeerplaats','terrace'=>'Terras','garden'=>'Tuin','solarium'=>'Dakterras','storage_room'=>'Berging','furnished'=>'Gemeubileerd','sea_views'=>'Uitzicht op zee','new_build'=>'Nieuwbouw','featured'=>'Uitgelichte woning'],'details'=>['town'=>'Plaats','province'=>'Provincie','country'=>'Land','location_detail'=>'Gedetailleerde locatie','price'=>'Prijs','operation'=>'Transactie','energy_consumption'=>'Energieverbruik','emissions'=>'Uitstoot','reference'=>'Referentie','source_date'=>'Brondatum']],
'profile_page'=>['kicker'=>'Account','title'=>'Mijn profiel','intro'=>'Beheer uw gegevens en beveiliging op één plek.','back_to_backoffice'=>'Terug naar beheer','back_home'=>'Terug naar home','role'=>'Rol','email_status'=>'E-mailstatus','verified'=>'Bevestigd','verification_pending'=>'Bevestiging in afwachting','member_since'=>'Lid sinds','no_date'=>'Geen datum','manage_account'=>'Account beheren','go_to_settings'=>'Naar instellingen','verification_sent'=>'Er is een nieuwe bevestigingslink verzonden.'],
'profile'=>['access_title'=>'Toegangsgegevens','access_intro'=>'Werk uw naam en primaire e-mailadres bij.','full_name'=>'Volledige naam','email'=>'E-mailadres','email_unverified'=>'E-mailadres nog niet bevestigd.','email_verify_help'=>'Bevestig het adres om uw account te beveiligen.','resend_link'=>'Link opnieuw verzenden','save_changes'=>'Wijzigingen opslaan','profile_updated'=>'Profiel bijgewerkt','security_title'=>'Accountbeveiliging','security_intro'=>'Gebruik een sterk wachtwoord.','current_password'=>'Huidig wachtwoord','new_password'=>'Nieuw wachtwoord','confirm_password'=>'Nieuw wachtwoord bevestigen','update_password'=>'Wachtwoord bijwerken','password_updated'=>'Wachtwoord bijgewerkt','danger_title'=>'Account verwijderen','danger_intro'=>'Hiermee wordt uw toegang permanent verwijderd.','delete_password'=>'Huidig wachtwoord ter bevestiging','password_placeholder'=>'Voer uw wachtwoord in','delete_warning'=>'Verwijderen kan niet ongedaan worden gemaakt.','delete_account'=>'Account verwijderen'],
]);
