<?php
$en = require __DIR__.'/../en/ui.php';
return array_replace_recursive($en, [
 'nav'=>['home'=>'Home','properties'=>'Woningen','about'=>'Over ons','environment'=>'Regio’s','contact'=>'Contact','favorites'=>'Favorieten','language'=>'Taal'],
 'common'=>['search'=>'Zoeken','show'=>'Tonen','apply_filters'=>'Filters toepassen','reset_filters'=>'Filters wissen','more_filters'=>'Meer filters','contact_us'=>'Neem contact op','send_message'=>'Bericht verzenden','send_request'=>'Aanvraag verzenden','view_favorites'=>'Favorieten bekijken','view_catalog'=>'Aanbod bekijken','save'=>'Opslaan','from'=>'Vanaf','to'=>'Tot','explore_properties'=>'Woningen bekijken','featured'=>'Uitgelicht'],
 'home'=>['title'=>'Home','quick_search_title'=>'Vind uw volgende woning','search_placeholder'=>'Regio, plaats, referentie…','any_zone'=>'Alle regio’s','any_type'=>'Alle woningtypen','max_budget'=>'Maximaal budget','any_budget'=>'Elke prijs','properties_count'=>':count woningen','location_placeholder'=>'Locatie','property_type'=>'Woningtype','min_price'=>'Vanaf EUR','max_price'=>'Tot EUR','latest_heading'=>'Nieuwste woningen','latest_subtitle'=>'De nieuwste toevoegingen aan ons aanbod.'],
 'properties'=>['page_title'=>'Woningen te koop','intro'=>'Bekijk het aanbod en bewaar uw favorieten met één klik.','empty'=>'Geen woningen gevonden.','featured_space'=>'Oppervlakte op aanvraag','location_pending'=>'Locatie op aanvraag','type_fallback'=>'Woning','summary_title'=>'Kort overzicht','summary_labels'=>['type'=>'Type','space'=>'Ruimte','operation'=>'Beschikbaarheid','default'=>'Overzicht'],'description_title'=>'Beschrijving','description_intro'=>'Een helder overzicht van wat deze woning biedt en waarom ze bij u kan passen.','description_pending'=>'We werken momenteel aan de volledige beschrijving.','related'=>'Vergelijkbare woningen','related_subtitle'=>'Meer opties in dezelfde regio of categorie.','contact_title'=>'Informatie aanvragen','contact_intro'=>'Laat weten hoe we u kunnen bereiken voor meer informatie over :title.','name'=>'Volledige naam','email'=>'E-mail','phone'=>'Telefoon','accept_terms'=>'Ik geef toestemming om mijn gegevens te gebruiken voor deze aanvraag.','request_information'=>'Informatie aanvragen','favorites_title'=>'Uw favoriete woningen','favorites_intro'=>'Hier vindt u snel de woningen terug die u hebt bewaard.','favorites_empty_title'=>'U hebt nog geen woningen bewaard','favorites_empty_body'=>'Woningen die u als favoriet markeert verschijnen hier.','saved'=>'Bewaard','favorite'=>'Favoriet','favorite_added'=>'Woning toegevoegd aan favorieten.','favorite_removed'=>'Woning verwijderd uit favorieten.','bedrooms'=>'Slaapkamers','bathrooms'=>'Badkamers','surface'=>'Oppervlakte','type'=>'Type','photos'=>'foto|foto’s','results_count'=>'{0} Geen resultaten|{1} :count woning|[2,*] :count woningen','stats'=>['bedrooms_short'=>'slpk.','bathrooms_short'=>'badk.'],'sort'=>['title'=>'Sortering en resultaten','subtitle'=>'Sorteer de lijst om sneller de juiste woning te vinden.','label'=>'Sorteren op','latest'=>'Nieuwste eerst','price_asc'=>'Prijs: laag naar hoog','price_desc'=>'Prijs: hoog naar laag','area_desc'=>'Oppervlakte: groot naar klein','area_asc'=>'Oppervlakte: klein naar groot','oldest'=>'Oudste eerst'],'filters'=>['search'=>'Vrij zoeken','search_placeholder'=>'Regio, referentie, titel of locatie','type'=>'Woningtype','zone'=>'Regio','minimum_area'=>'Minimale oppervlakte','town'=>'Plaats','price_range'=>'Prijsklasse','min_price'=>'Minimumprijs','max_price'=>'Maximumprijs','features'=>'Kenmerken','others'=>'Overig','bedrooms'=>'Slaapkamers','bathrooms'=>'Badkamers','select'=>'Selecteren','pool'=>'Zwembad','terrace'=>'Terras','garden'=>'Tuin','solar'=>'Perceel','patio'=>'Patio','up_to'=>'Tot :price EUR']],
 'about'=>['title'=>'Over ons','contact_title'=>'Neem contact op','name'=>'Uw naam','email'=>'Uw e-mail','message'=>'Uw bericht','name_placeholder'=>'Vul uw naam in','email_placeholder'=>'voorbeeld@email.com','message_placeholder'=>'Schrijf uw bericht'],
 'contact'=>['title'=>'Contact','info_title'=>'Contactgegevens','message_title'=>'Stuur ons een bericht','phone_pending'=>'Nog niet ingesteld','email_pending'=>'Nog niet ingesteld','address_pending'=>'Adres nog niet ingesteld','name'=>'Naam','email'=>'E-mail','message'=>'Bericht','name_placeholder'=>'Vul uw naam in','email_placeholder'=>'Vul uw e-mail in','message_placeholder'=>'Schrijf uw bericht','accept_terms'=>'Ik ga akkoord met de voorwaarden','success'=>'Bedankt voor uw bericht. We nemen spoedig contact met u op.'],
 'environment'=>['title'=>'Regio’s','intro'=>'Ontdek de regio’s waar wij actief zijn, hun leefomgeving en het beschikbare woningaanbod.','interactive_map'=>'Interactieve kaart','properties_in'=>'Woningen in :name','view_more'=>'Meer bekijken'],
 'search'=>['title'=>'Zoekresultaten','heading'=>'Zoekresultaten','empty'=>'Geen woningen passen bij uw zoekopdracht.','view_more'=>'Meer bekijken'],
 'auth'=>['register_title'=>'Account aanmaken','register_heading'=>'Registreren','login_title'=>'Inloggen','login_heading'=>'Welkom terug','remember_me'=>'Onthoud mij','forgot_password'=>'Wachtwoord vergeten?','forgot_password_intro'=>'Vul uw e-mailadres in en wij sturen een link om uw wachtwoord opnieuw in te stellen.','send_reset_link'=>'Herstellink verzenden','reset_password'=>'Wachtwoord herstellen','verify_email_intro'=>'Bevestig uw e-mailadres via de link die wij u hebben gestuurd.','verify_email_sent'=>'Er is een nieuwe bevestigingslink naar uw e-mailadres verzonden.','resend_verification'=>'Bevestigingsmail opnieuw verzenden','logout'=>'Uitloggen','confirm_password_intro'=>'Dit is een beveiligd gedeelte. Bevestig uw wachtwoord om verder te gaan.','confirm'=>'Bevestigen','full_name'=>'Volledige naam','email'=>'E-mail','password'=>'Wachtwoord','confirm_password'=>'Wachtwoord bevestigen','role'=>'Rol','user'=>'Gebruiker','admin'=>'Beheerder','create_account'=>'Account aanmaken','already_have_account'=>'Hebt u al een account?','login'=>'Inloggen'],
 'property_types'=>['piso'=>'Appartement','casa'=>'Huis','villa'=>'Villa'],
]);
