<?php
$en=require __DIR__.'/../en/frontend.php';
return array_replace_recursive($en,[
'site_defaults'=>['footer_text'=>'Alla rättigheter förbehållna.','contact_intro'=>'Vi hjälper dig att hitta rätt bostad och svarar på dina frågor.','about_heading'=>'Vårt arbetssätt','about_body'=>'Domatia erbjuder utvalda bostäder med tydlig och personlig rådgivning.','home_hero_badge'=>'Fastighetsexpertis du kan lita på','home_hero_title'=>'Upptäck unika bostäder','home_hero_subtitle'=>'På de mest eftertraktade platserna','home_search_button_text'=>'Sök','home_value_1'=>'Noggrant utvalda bostäder','home_value_2'=>'Personlig vägledning från början till slut','home_value_3'=>'En tydlig process för ett lyckat köp','home_featured_heading'=>'Utvalda bostäder','home_featured_subtitle'=>'Ett omsorgsfullt urval av det bästa i vårt utbud.','home_cta_heading'=>'Vi följer dig genom hela köpet','home_cta_body'=>'Från första visningen till avslutet erbjuder vi tydlig och personlig vägledning.','home_cta_primary_text'=>'Visa bostäder','home_cta_secondary_text'=>'Kontakt','about_header_title'=>'Om oss','contact_header_title'=>'Kontakta oss','environment_header_title'=>'Upptäck områdena','register_header_title'=>'Skapa konto'],
'common'=>['image_of'=>'Bild av :title','reference_short'=>'Ref.','pending'=>'Avvaktar','photos'=>'{1} :count foto|[2,*] :count foton'],'contact'=>['map'=>'Karta','phone_prefix'=>'Telefon:','email_prefix'=>'E-post:'],'environment'=>['title'=>'Områden','intro'=>'Upptäck våra områden, deras omgivningar och tillgängliga bostäder.'],
'properties'=>['filter_title'=>'Filtrera bostäder','filter_intro'=>'Förfina sökningen för att snabbt hitta rätt bostad.','favorites_kicker'=>'Sparat urval','favorites_count'=>'{1} :count sparad bostad|[2,*] :count sparade bostäder','type_in_location'=>':type i :location','video'=>'Visa video','virtual_tour'=>'Virtuell visning','technical_sheet'=>'Bostadsdetaljer','highlighted_features'=>'Viktiga egenskaper','map_location'=>'Plats på kartan','contact_default_message'=>'Förfrågan om :title (:reference)','name_placeholder'=>'Ditt namn','features'=>['pool'=>'Pool','patio'=>'Trädgård eller uteplats','plot_available'=>'Tomt tillgänglig','plot_area'=>':area m² tomt','air_conditioning'=>'Luftkonditionering','garage'=>'Garage','lift'=>'Hiss','parking'=>'Parkering','terrace'=>'Terrass','garden'=>'Trädgård','solarium'=>'Solterrass','storage_room'=>'Förråd','furnished'=>'Möblerad','sea_views'=>'Havsutsikt','new_build'=>'Nyproduktion','featured'=>'Utvald bostad'],'details'=>['town'=>'Ort','province'=>'Provins','country'=>'Land','location_detail'=>'Detaljerat område','price'=>'Pris','operation'=>'Transaktion','energy_consumption'=>'Energiförbrukning','emissions'=>'Utsläpp','reference'=>'Referens','source_date'=>'Källdatum']],
'profile_page'=>['kicker'=>'Konto','title'=>'Min profil','intro'=>'Hantera dina uppgifter och kontots säkerhet på ett ställe.','back_to_backoffice'=>'Tillbaka till administrationen','back_home'=>'Tillbaka till hem','role'=>'Roll','email_status'=>'E-poststatus','verified'=>'Bekräftad','verification_pending'=>'Väntar på bekräftelse','member_since'=>'Medlem sedan','no_date'=>'Inget datum','manage_account'=>'Hantera konto','go_to_settings'=>'Till inställningar','verification_sent'=>'En ny bekräftelselänk har skickats.'],
'profile'=>['access_title'=>'Inloggningsuppgifter','access_intro'=>'Uppdatera namn och primär e-postadress.','full_name'=>'Fullständigt namn','email'=>'E-postadress','email_unverified'=>'E-postadressen är inte bekräftad.','email_verify_help'=>'Bekräfta adressen för att skydda kontot.','resend_link'=>'Skicka länken igen','save_changes'=>'Spara ändringar','profile_updated'=>'Profilen har uppdaterats','security_title'=>'Kontosäkerhet','security_intro'=>'Använd ett starkt lösenord.','current_password'=>'Nuvarande lösenord','new_password'=>'Nytt lösenord','confirm_password'=>'Bekräfta nytt lösenord','update_password'=>'Uppdatera lösenord','password_updated'=>'Lösenordet har uppdaterats','danger_title'=>'Ta bort konto','danger_intro'=>'Detta tar permanent bort din åtkomst.','delete_password'=>'Nuvarande lösenord för bekräftelse','password_placeholder'=>'Ange ditt lösenord','delete_warning'=>'Åtgärden kan inte ångras.','delete_account'=>'Ta bort konto'],
]);
