<?php
$en = require __DIR__.'/../en/ui.php';
return array_replace_recursive($en, [
 'nav'=>['home'=>'Hem','properties'=>'Bostäder','about'=>'Om oss','environment'=>'Områden','contact'=>'Kontakt','favorites'=>'Favoriter','language'=>'Språk'],
 'common'=>['search'=>'Sök','show'=>'Visa','apply_filters'=>'Använd filter','reset_filters'=>'Rensa filter','more_filters'=>'Fler filter','contact_us'=>'Kontakta oss','send_message'=>'Skicka meddelande','send_request'=>'Skicka förfrågan','view_favorites'=>'Visa favoriter','view_catalog'=>'Visa utbud','save'=>'Spara','from'=>'Från','to'=>'Till','explore_properties'=>'Utforska bostäder','featured'=>'Utvald'],
 'home'=>['title'=>'Hem','quick_search_title'=>'Hitta ditt nästa hem','search_placeholder'=>'Område, ort, referens…','any_zone'=>'Alla områden','any_type'=>'Alla bostadstyper','max_budget'=>'Högsta budget','any_budget'=>'Valfritt pris','properties_count'=>':count bostäder','location_placeholder'=>'Plats','property_type'=>'Bostadstyp','min_price'=>'Från EUR','max_price'=>'Till EUR','latest_heading'=>'Senaste bostäderna','latest_subtitle'=>'De senaste objekten i vårt utbud.'],
 'properties'=>['page_title'=>'Bostäder till salu','intro'=>'Utforska utbudet och spara favoriter med ett klick.','empty'=>'Inga bostäder hittades.','featured_space'=>'Yta bekräftas senare','location_pending'=>'Plats bekräftas senare','type_fallback'=>'Bostad','summary_title'=>'Snabböversikt','summary_labels'=>['type'=>'Typ','space'=>'Utrymme','operation'=>'Tillgänglighet','default'=>'Översikt'],'description_title'=>'Bostadsbeskrivning','description_intro'=>'En tydlig överblick över vad bostaden erbjuder och varför den kan passa dig.','description_pending'=>'Vi färdigställer den fullständiga beskrivningen.','related'=>'Liknande bostäder','related_subtitle'=>'Fler alternativ i samma område eller kategori.','contact_title'=>'Begär information','contact_intro'=>'Berätta hur vi kan nå dig angående :title.','name'=>'Fullständigt namn','email'=>'E-post','phone'=>'Telefon','accept_terms'=>'Jag godkänner att mina uppgifter används för att besvara denna förfrågan.','request_information'=>'Begär information','favorites_title'=>'Dina favoritbostäder','favorites_intro'=>'Här hittar du snabbt tillbaka till sparade bostäder.','favorites_empty_title'=>'Du har inte sparat några bostäder ännu','favorites_empty_body'=>'Bostäder som markeras som favoriter visas här.','saved'=>'Sparad','favorite'=>'Favorit','favorite_added'=>'Bostaden har lagts till i favoriter.','favorite_removed'=>'Bostaden har tagits bort från favoriter.','bedrooms'=>'Sovrum','bathrooms'=>'Badrum','surface'=>'Yta','type'=>'Typ','photos'=>'foto|foton','results_count'=>'{0} Inga resultat|{1} :count bostad|[2,*] :count bostäder','stats'=>['bedrooms_short'=>'sovr.','bathrooms_short'=>'badr.'],'sort'=>['title'=>'Sortering och resultat','subtitle'=>'Sortera listan för att hitta rätt bostad snabbare.','label'=>'Sortera efter','latest'=>'Nyast först','price_asc'=>'Pris: lägst först','price_desc'=>'Pris: högst först','area_desc'=>'Yta: störst först','area_asc'=>'Yta: minst först','oldest'=>'Äldst först'],'filters'=>['search'=>'Fritextsökning','search_placeholder'=>'Område, referens, titel eller plats','type'=>'Bostadstyp','zone'=>'Område','minimum_area'=>'Minsta yta','town'=>'Ort','price_range'=>'Prisintervall','min_price'=>'Lägsta pris','max_price'=>'Högsta pris','features'=>'Egenskaper','others'=>'Övrigt','bedrooms'=>'Sovrum','bathrooms'=>'Badrum','select'=>'Välj','pool'=>'Pool','terrace'=>'Terrass','garden'=>'Trädgård','solar'=>'Tomt','patio'=>'Uteplats','up_to'=>'Upp till :price EUR']],
 'about'=>['title'=>'Om oss','contact_title'=>'Kontakta oss','name'=>'Ditt namn','email'=>'Din e-post','message'=>'Ditt meddelande','name_placeholder'=>'Ange ditt namn','email_placeholder'=>'exempel@email.com','message_placeholder'=>'Skriv ditt meddelande'],
 'contact'=>['title'=>'Kontakt','info_title'=>'Kontaktuppgifter','message_title'=>'Skicka ett meddelande','phone_pending'=>'Inte angivet ännu','email_pending'=>'Inte angivet ännu','address_pending'=>'Adress inte angiven','name'=>'Namn','email'=>'E-post','message'=>'Meddelande','name_placeholder'=>'Ange ditt namn','email_placeholder'=>'Ange din e-post','message_placeholder'=>'Skriv ditt meddelande','accept_terms'=>'Jag godkänner villkoren','success'=>'Tack för ditt meddelande. Vi kontaktar dig snart.'],
 'environment'=>['title'=>'Områden','intro'=>'Upptäck områdena där vi arbetar, deras livsstil, omgivningar och tillgängliga bostäder.','interactive_map'=>'Interaktiv karta','properties_in'=>'Bostäder i :name','view_more'=>'Visa mer'],
 'search'=>['title'=>'Sökresultat','heading'=>'Sökresultat','empty'=>'Inga bostäder matchar din sökning.','view_more'=>'Visa mer'],
 'auth'=>['register_title'=>'Skapa konto','register_heading'=>'Registrera','login_title'=>'Logga in','login_heading'=>'Välkommen tillbaka','remember_me'=>'Kom ihåg mig','forgot_password'=>'Glömt lösenordet?','forgot_password_intro'=>'Ange din e-post så skickar vi en länk för att återställa lösenordet.','send_reset_link'=>'Skicka återställningslänk','reset_password'=>'Återställ lösenord','verify_email_intro'=>'Bekräfta din e-postadress via länken vi har skickat.','verify_email_sent'=>'En ny bekräftelselänk har skickats.','resend_verification'=>'Skicka bekräftelsen igen','logout'=>'Logga ut','confirm_password_intro'=>'Detta är en skyddad del. Bekräfta lösenordet för att fortsätta.','confirm'=>'Bekräfta','full_name'=>'Fullständigt namn','email'=>'E-post','password'=>'Lösenord','confirm_password'=>'Bekräfta lösenord','role'=>'Roll','user'=>'Användare','admin'=>'Administratör','create_account'=>'Skapa konto','already_have_account'=>'Har du redan ett konto?','login'=>'Logga in'],
 'property_types'=>['piso'=>'Lägenhet','casa'=>'Hus','villa'=>'Villa'],
]);
